version: '3.9'
services:
  node-ecom:
    build: 
      context: .
      args: 
        NODE_ENV : development
    image: "node-ecom-image:1.0.0"
    container_name: node-ecom
    ports:
      - "4000:3000"
    env_file:
      - ./config/.env